DROP DATABASE IF EXISTS employee_tracker;
CREATE DATABASE employee_tracker;

USE employee_tracker;

CREATE TABLE department (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL
);

CREATE TABLE role (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL,
  title VARCHAR(30) NOT NULL,
  salary DECIMAL(8,2)
  department_id INT AUTO_INCREMENT,
  FOREIGN KEY (department)
  REFERENCES department(id)
  ON DELETE SET NULL
);

CREATE TABLE employee (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  role_id INT AUTO_INCREMENT,
  manager_id INT AUTO_INCREMENT,
  FOREIGN KEY (role)
  REFERENCES role(id)
  FOREIGN KEY (manager)
  REFERENCES manager(id)
  ON DELETE SET NULL
);